// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v3.6.1

import { Writer, Reader } from "as-proto/assembly";
import { DiceRoll } from "./DiceRoll";

export class DiceSeries {
  static encode(message: DiceSeries, writer: Writer): void {
    const rolls = message.rolls;
    for (let i: i32 = 0; i < rolls.length; ++i) {
      writer.uint32(10);
      writer.fork();
      DiceRoll.encode(rolls[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): DiceSeries {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DiceSeries();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.rolls.push(DiceRoll.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  rolls: Array<DiceRoll>;

  constructor(rolls: Array<DiceRoll> = []) {
    this.rolls = rolls;
  }
}
