// Code generated by @apexlang/codegen. DO NOT EDIT.

package guest01

import (
	"github.com/wapc/tinygo-msgpack"
	"github.com/wapc/tinygo-msgpack/convert"
)

var _ = convert.Package

type GreeterSayHelloArgs struct {
	FirstName string `json:"firstName" yaml:"firstName" msgpack:"firstName"`
	LastName  string `json:"lastName" yaml:"lastName" msgpack:"lastName"`
}

func (o *GreeterSayHelloArgs) Decode(decoder msgpack.Reader) error {
	numFields, err := decoder.ReadMapSize()
	if err != nil {
		return err
	}

	for numFields > 0 {
		numFields--
		field, err := decoder.ReadString()
		if err != nil {
			return err
		}
		switch field {
		case "firstName":
			o.FirstName, err = decoder.ReadString()
		case "lastName":
			o.LastName, err = decoder.ReadString()
		default:
			err = decoder.Skip()
		}
		if err != nil {
			return err
		}
	}

	return nil
}

func (o *GreeterSayHelloArgs) Encode(encoder msgpack.Writer) error {
	if o == nil {
		encoder.WriteNil()
		return nil
	}
	encoder.WriteMapSize(2)
	encoder.WriteString("firstName")
	encoder.WriteString(o.FirstName)
	encoder.WriteString("lastName")
	encoder.WriteString(o.LastName)

	return nil
}
